# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Reatil Store' do

pod ‘Realm'
pod 'IDMPhotoBrowser'

end

target 'Reatil StoreTests' do

end

target 'Reatil StoreUITests' do

end

